platform:ios, '11.0'
inhibit_all_warnings!

target 'UITestingSnapshot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UITestingSnapshot

  target 'UITestingSnapshotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITestingSnapshotUITests' do
    # Pods for testing
    pod 'iOSSnapshotTestCase'
  end

end
